//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        public int id { get; set; }
        public Nullable<bool> is_actual { get; set; }
        public Nullable<int> adress_type { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<int> individual { get; set; }
        public Nullable<int> legal_user { get; set; }
        public Nullable<int> street { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_Date { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AdressType AdressType { get; set; }
        public virtual City City1 { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Street Street1 { get; set; }
    }
}
