//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int id { get; set; }
        public string number { get; set; }
        public Nullable<int> legal_user { get; set; }
        public Nullable<int> bill_type { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_Date { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual BillType BillType { get; set; }
    }
}
